baseurl = "https://gonapps.com"
title = "gonapps.com"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "gonapps"

[params]
    author = "Gonapps"
    description = "An Official Site of Gon Apps"
    keywords = "homepage, developer"
    info = "I AM A PROGRAMMER!"

    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "About"
    weight = 1
    url = "/about/"

[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/gonapps/"

[[params.social]]
    name = "Projects"
    weight = 3
    url = "/projects/"

[[params.social]]
    name = "Live Projects"
    weight = 4
    url = "/live-projects/"

[[params.social]]
    name = "Blog"
    weight = 5
    url = "/blog/"

[[params.social]]
    name = "Youtube"
    weight = 6
    url = "https://www.youtube.com/channel/UCJWwG8T5gFXLWzePLc1qu1A"

[[params.social]]
    name = "LinkedIn"
    weight = 7
    url = "https://www.linkedin.com/in/gonapps/"

[[params.social]]
    name = "Twitter"
    weight = 8
    url = "https://twitter.com/gonapps/"

[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"

[[menu.main]]
    name = "Live Projects"
    weight = 2
    url  = "/live-projects/"

[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/blog/"

[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"

