baseurl = "https://gonnux.com"
title = "gonnux.com"

theme = "hugo-apps-theme"

languagecode = "en"
disqusShortname = "gonnux"
googleAnalytics = "UA-66175317-1"

[params]
  googleAutoAds = "ca-pub-8314195422970862"
  avatar = "/img/gonapps.png"
  author = "Gonnux"
  description = "The Official Site of Gonnux"
  keywords = "homepage, developer"
  info = "The Official Site of Binkoni"

  hideCredits = true
  hideCopyright = true

  # Custom CSS
  custom_css = []

  # RTL support
  rtl = false

[[params.social]]
  name = "About"
  weight = 1
  url = "/about/"

[[params.social]]
  name = "Github"
  weight = 2
  url = "https://github.com/binkoni/"

[[params.social]]
  name = "Apps"
  weight = 3
  url = "/apps/"

[[params.social]]
  name = "Projects"
  weight = 3
  url = "/projects/"

[[params.social]]
  name = "Blog"
  weight = 4
  url = "/blog/"

[[params.social]]
  name = "Youtube"
  weight = 5
  url = "https://www.youtube.com/channel/UC0ryyWXkCMuXp8jmhjLEjpw"

[[params.social]]
    name = "LinkedIn"
    weight = 6
    url = "https://www.linkedin.com/in/binkoni"

[[params.social]]
  name = "Twitter"
  weight = 7
  url = "https://twitter.com/gonnux/"

[[menu.main]]
  name = "Apps"
  weight = 1
  url  = "/apps/"

[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "/projects/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "/blog/"

[[menu.main]]
  name = "About"
  weight = 3
  url = "/about/"

[taxonomies]
  tag = "tags"
