baseurl = "https://gonapps.com"
title = "gonapps.com"

theme = "hugo-apps-theme"

languagecode = "en"

paginate = 20
canonifyurls = true

disqusShortname = "gonapps"
googleAnalytics = "UA-66175317-1"

[params]
    googleAutoAds = "ca-pub-8314195422970862"
    avatar = "/img/gonapps.png"
    author = "Gonapps"
    description = "An Official Site of Gon Apps"
    keywords = "homepage, developer"
    info = "I AM A PROGRAMMER!"

    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "About"
    weight = 1
    url = "/about/"

[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/gonapps/"

[[params.social]]
    name = "Apps"
    weight = 3
    url = "/apps/"

[[params.social]]
    name = "Blog"
    weight = 4
    url = "/blog/"

[[params.social]]
    name = "Youtube"
    weight = 5
    url = "https://www.youtube.com/channel/UCJWwG8T5gFXLWzePLc1qu1A"

[[params.social]]
    name = "LinkedIn"
    weight = 6
    url = "https://www.linkedin.com/in/gonapps/"

[[params.social]]
    name = "Twitter"
    weight = 7
    url = "https://twitter.com/gonapps/"

[[menu.main]]
    name = "Apps"
    weight = 1
    url  = "/apps/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/blog/"

[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"

